const text=(v:unknown)=>typeof v==="string"?v.trim():v==null?"":String(v).trim();
export function normalizeAdmissionId(v:unknown){const s=text(v).toUpperCase().replace(/\s+/g,"");return s||null}
export function normalizeIndianMobile(v:unknown){const original=text(v);let d=original.replace(/\D/g,"");if(d.length===11&&d.startsWith("0"))d=d.slice(1);if(d.length===12&&d.startsWith("91"))d=d.slice(2);return /^[6-9]\d{9}$/.test(d)?`+91${d}`:null}
export function parseCurrency(v:unknown){if(v==null||text(v)==="")return 0;const n=Number(text(v).replace(/[₹,\s]/g,"").replace(/[^\d.-]/g,""));return Number.isFinite(n)?n:0}
export function parseSheetDate(v:unknown):Date|null {if(v instanceof Date&&!isNaN(v.valueOf()))return v;if(typeof v==="number"&&v>0){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return isNaN(d.valueOf())?null:d}const s=text(v);if(!s)return null;let m=s.match(/^(\d{2})[/-](\d{2})[/-](\d{4})$/);if(m){const d=new Date(Date.UTC(+m[3],+m[2]-1,+m[1]));return d.getUTCDate()===+m[1]&&d.getUTCMonth()===+m[2]-1?d:null}const d=new Date(s);return isNaN(d.valueOf())?null:new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate()))}
const plans:Record<string,{code:string;days:number}>={"30":{code:"PLAN_30_DAYS",days:30},"1MONTH":{code:"PLAN_30_DAYS",days:30},"1M":{code:"PLAN_30_DAYS",days:30},"30DAYS":{code:"PLAN_30_DAYS",days:30},"90":{code:"PLAN_90_DAYS",days:90},"3MONTH":{code:"PLAN_90_DAYS",days:90},"3MONTHS":{code:"PLAN_90_DAYS",days:90},"3M":{code:"PLAN_90_DAYS",days:90},"90DAYS":{code:"PLAN_90_DAYS",days:90},"180":{code:"PLAN_180_DAYS",days:180},"6MONTH":{code:"PLAN_180_DAYS",days:180},"6MONTHS":{code:"PLAN_180_DAYS",days:180},"6M":{code:"PLAN_180_DAYS",days:180},"180DAYS":{code:"PLAN_180_DAYS",days:180},"365":{code:"PLAN_365_DAYS",days:365},"1YEAR":{code:"PLAN_365_DAYS",days:365},"1Y":{code:"PLAN_365_DAYS",days:365},"12MONTH":{code:"PLAN_365_DAYS",days:365},"12MONTHS":{code:"PLAN_365_DAYS",days:365},"365DAYS":{code:"PLAN_365_DAYS",days:365}};
const planKey=(v:unknown)=>text(v).toUpperCase().replace(/[^A-Z0-9]/g,"");
export function mapPlan(v:unknown){return plans[planKey(v)]??null}
export function resolvePlan(v:unknown,sourceSheet:unknown,start:Date|null,end:Date|null){const direct=mapPlan(v);if(direct)return {...direct,isCustom:false};const key=planKey(v);if(key.includes("CUSTOM")){const days=start&&end&&end>=start?Math.round((end.valueOf()-start.valueOf())/86400000)+1:null;return {code:null,days,isCustom:true}}const sheetKey=planKey(sourceSheet).replace(/^RENEWALS?/,"");const fallback=plans[sheetKey]??null;if(fallback)return {...fallback,isCustom:false};if(!start||!end||end<start)return null;const days=Math.round((end.valueOf()-start.valueOf())/86400000)+1;const inferred=days>=28&&days<=31?plans["30"]:days>=89&&days<=92?plans["90"]:days>=179&&days<=184?plans["180"]:days>=364&&days<=366?plans["365"]:null;return inferred?{...inferred,isCustom:false}:null}
export function cleanOptional(v:unknown){return text(v)||null}
