import bcrypt from "bcryptjs";import {prisma} from "@/lib/database/prisma";import type {MembershipSheetAdapter,RawMembershipRow} from "@/types/sheets";import {calculateMembershipStatus,calculatePaymentStatus} from "@/lib/utils/status";import {cleanOptional,resolvePlan,normalizeAdmissionId,normalizeIndianMobile,parseCurrency,parseSheetDate} from "@/lib/utils/normalization";import {upsertMember} from "@/repositories/member.repository";
const blank=(r:RawMembershipRow)=>Object.entries(r).filter(([k])=>!["sourceSheet","sourceRow"].includes(k)).every(([,v])=>v==null||String(v).trim()==="");
const withImportSource=(row:RawMembershipRow,index:number)=>{const sourceSheet=cleanOptional(row.sourceSheet)??"Google Sheets";const candidate=Number(row.sourceRow);const sourceRow=Number.isInteger(candidate)&&candidate>0?candidate:index+1;return {...row,sourceSheet,sourceRow}};
export async function runImport(adapter:MembershipSheetAdapter,initiatedBy:string){
 const initialPin=process.env.MEMBER_INITIAL_PIN;if(initialPin&&initialPin.length<8)throw new Error("MEMBER_INITIAL_PIN must contain at least 8 characters");const initialPinHash=initialPin?await bcrypt.hash(initialPin,12):null;const rows=await adapter.fetchMembershipRows();const batch=await prisma.importBatch.create({data:{initiatedBy,status:"PROCESSING",totalRows:rows.length}});const counts={successfulRows:0,updatedRows:0,skippedRows:0,warningRows:0,failedRows:0};
 for(const [index,inputRow] of rows.entries()){const row=withImportSource(inputRow,index);try{
  if(blank(row)){counts.skippedRows++;continue}const admissionId=normalizeAdmissionId(row.admissionId);if(!admissionId)throw new Error("Admission ID is required");
  const result=await prisma.$transaction(async tx=>{
   const existing=await tx.member.findUnique({where:{admissionId}});const mobile=normalizeIndianMobile(row.mobile);const warnings:string[]=[];
   const member=await upsertMember(tx,admissionId,{fullName:cleanOptional(row.name)??existing?.fullName??"Unknown member",mobileNumber:mobile,originalMobileNumber:cleanOptional(row.mobile),gender:cleanOptional(row.gender),ageAtImport:Number(row.age)||null,birthDate:parseSheetDate(row.birthDate),address:cleanOptional(row.address),medicalHistory:cleanOptional(row.medicalHistory),sourceSheet:row.sourceSheet,sourceRow:row.sourceRow});if(initialPinHash&&member.mobileNumber&&!await tx.user.findUnique({where:{memberId:member.id}})){const userWithMobile=await tx.user.findUnique({where:{mobileNumber:member.mobileNumber}});if(userWithMobile)warnings.push("Member login was not provisioned because this mobile number is already in use.");else await tx.user.create({data:{memberId:member.id,mobileNumber:member.mobileNumber,pinHash:initialPinHash,role:"MEMBER",mustChangePassword:true}})}
   const found=await tx.membership.findUnique({where:{sourceSheet_sourceRow:{sourceSheet:row.sourceSheet,sourceRow:row.sourceRow}}});const start=parseSheetDate(row.startDate),end=parseSheetDate(row.endDate);const plan=resolvePlan(row.plan,row.sourceSheet,start,end);if(!plan)warnings.push(`Unknown membership plan: ${cleanOptional(row.plan)??"blank"}`);const planRecord=plan?.code?await tx.membershipPlan.findUnique({where:{planCode:plan.code}}):null;
   const final=parseCurrency(row.finalAmount),paid=parseCurrency(row.amountPaid),pending=parseCurrency(row.pendingAmount);const status=calculateMembershipStatus(start,end),payment=calculatePaymentStatus(final,paid,pending);const data={memberId:member.id,planId:planRecord?.id??null,planDays:plan?.days??null,category:cleanOptional(row.category),startDate:start,endDate:end,totalAmount:parseCurrency(row.totalAmount),discountAmount:parseCurrency(row.discount),finalAmount:final,amountPaid:paid,pendingAmount:pending,paymentMode:cleanOptional(row.paymentMode),paymentStatus:payment,sourcePaymentStatus:cleanOptional(row.paymentStatus),membershipStatus:plan?status:"REVIEW_REQUIRED" as const,remarks:cleanOptional(row.remarks),sourceType:"LEGACY_IMPORT" as const,sourceTimestamp:parseSheetDate(row.timestamp)};
   await tx.membership.upsert({where:{sourceSheet_sourceRow:{sourceSheet:row.sourceSheet,sourceRow:row.sourceRow}},create:{...data,sourceSheet:row.sourceSheet,sourceRow:row.sourceRow},update:data});await tx.migrationLog.create({data:{batchId:batch.id,sourceSheet:row.sourceSheet,sourceRow:row.sourceRow,admissionId,status:warnings.length?"WARNING":found?"UPDATED":"MIGRATED",warningMessage:warnings.join("; ")||null,rawData:row as object}});return {updated:!!found,warn:!!warnings.length};
  });result.updated?counts.updatedRows++:counts.successfulRows++;if(result.warn)counts.warningRows++;
 }catch(error){counts.failedRows++;await prisma.migrationLog.create({data:{batchId:batch.id,sourceSheet:row.sourceSheet,sourceRow:row.sourceRow,admissionId:normalizeAdmissionId(row.admissionId),status:"FAILED",errorMessage:error instanceof Error?error.message:"Unknown error",rawData:row as object}})}}
 return prisma.importBatch.update({where:{id:batch.id},data:{...counts,completedAt:new Date(),status:counts.failedRows||counts.warningRows?"COMPLETED_WITH_WARNINGS":"COMPLETED"},include:{logs:true}});
}
