"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { membershipCategories, type MembershipCategory } from "@/constants/membership-packages";
import { membershipEndDate } from "@/lib/membership-dates";
import { PaymentCheckout, type PaymentOrder } from "./payment-checkout";

type Plan = { id: string; planName: string; category: string | null; durationDays: number; amount: string };
export function RenewalClient({ plans, orders, today, initialCategory, currentEnd }: { plans: Plan[]; orders: PaymentOrder[]; today: string; initialCategory: MembershipCategory; currentEnd: string | null }) {
  const router = useRouter();
  const [category, setCategory] = useState(initialCategory);
  const [start, setStart] = useState(today);
  const [order, setOrder] = useState<PaymentOrder | null>(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  async function renew(planId: string) {
    setBusy(true); setError("");
    try {
      const r = await fetch("/api/payments", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ planId, kind: "RENEWAL", startDate: start }) });
      const data = await r.json();
      if (!r.ok) throw new Error(data.error?.message ?? "Could not prepare renewal.");
      setOrder(data.data); router.refresh();
    } catch (e) { setError(e instanceof Error ? e.message : "Please try again."); }
    finally { setBusy(false); }
  }
  return <>
    <p className="visitor-message mt-5">{currentEnd ? `Your current membership ends ${currentEnd}. ` : ""}Your renewal starts on the date selected below. It does not automatically start after your current membership ends. The gym must verify your payment and approve the renewal.</p>
    <div className="mt-6 flex flex-wrap gap-2" role="group" aria-label="Renewal membership category">{membershipCategories.map(c => <button type="button" key={c.code} onClick={() => setCategory(c.code)} aria-pressed={category === c.code} className={category === c.code ? "visitor-button" : "visitor-secondary"}>{c.label}</button>)}</div>
    <p className="mt-3 text-sm text-white/60">{membershipCategories.find(c => c.code === category)?.note}</p>
    <label className="visitor-label mt-5 max-w-sm">Renewal start date<input type="date" required min="1900-01-01" max={today} value={start} onChange={e => setStart(e.target.value)} className="visitor-input"/><span className="mt-2 block text-xs text-white/50">Today or earlier only. The end date is generated by the system.</span></label>
    <div className="mt-6 grid gap-4 sm:grid-cols-2">{plans.filter(p => p.category === category).map(p => <article key={p.id} className="visitor-card"><h2 className="text-lg font-bold">{p.planName}</h2><p className="mt-3 text-3xl font-black text-zenith-300">₹{Number(p.amount).toLocaleString("en-IN")}</p><p className="mt-3 text-sm text-white/65">Ends: {start && /^\d{4}-\d{2}-\d{2}$/.test(start) ? membershipEndDate(start, p.durationDays) : "Choose start date"}</p><button type="button" disabled={busy || !start || start > today} onClick={() => renew(p.id)} className="visitor-button mt-5 w-full">{busy ? "Preparing…" : "Renew with UPI"}</button></article>)}</div>
    {!plans.some(p => p.category === category) && <p className="visitor-message mt-4">No plans are available for this category. Please contact the gym.</p>}
    {error && <p role="alert" className="visitor-message mt-4">{error}</p>}
    {order && <div className="mt-7 max-w-lg"><PaymentCheckout key={order.id} order={order} onClose={() => { setOrder(null); router.refresh(); }}/></div>}
    <section className="mt-8"><h2 className="text-xl font-bold">Your renewal requests</h2>{!orders.length && <p className="mt-3 text-sm text-white/50">Your requests will appear here.</p>}<div className="mt-4 space-y-3">{orders.map(o => <article key={o.id} className="visitor-card"><h3 className="font-bold">{o.planName} · ₹{o.amount}</h3><p className="mt-2 text-sm text-zenith-300">{o.status === "APPROVED" ? "Renewal approved" : o.status === "SUBMITTED" ? "Awaiting gym payment verification and approval" : o.status === "REJECTED" ? "Not approved — contact the gym" : "Awaiting payment reference"}</p><p className="mt-2 text-xs text-white/50">{o.startDate} – {o.endDate}</p>{["PENDING", "SUBMITTED"].includes(o.status) && <button type="button" onClick={() => setOrder(o)} className="visitor-secondary mt-4">{o.status === "PENDING" ? "Continue payment" : "View payment"}</button>}</article>)}</div></section>
  </>;
}
